import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString, Length, Matches } from 'class-validator';

export class TotpDisableInputDto {
  @ApiProperty({
    description: 'The one-time password (OTP) generated by the authenticator app.',
    example: '738239',
  })
  @IsString()
  @IsNotEmpty()
  @Length(6, 6)
  @Matches(/^\d+$/, { message: 'token must be a numeric string' })
  token: string;
}
